
const languages = {
  en: {
    home: 'Home',
    admins: 'Admins',
    stores: 'Stores',
    customers: 'Customers',
    specialty: 'Specialty',
    products: 'Products',
    orders: 'Orders',
    orderHistory: 'Order History',
    drivers: 'Drivers',
    reviews: 'Reviews',
    vouchers: 'Vouchers',
    paymentMethods: 'Payment Methods',
    logActivity: 'Log Activity',
    compSuggestions: 'Comp & Suggestions',
    logout: 'Log out',
    notes: 'Notes',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    result: 'Result',
    close: 'Close',
    tools: 'Tools',
    notification: 'Notification',
    profile: 'Profile',
    hi: 'Hi',
    pleaseEnterEmail: 'Please enter your email address. You will receive an email message to reset your password.',
    emailAddress: 'Email Address',
    requestPasswordReset: 'REQUEST PASSWORD RESET',
    login: 'Login',
    password: 'Password',
    logIn: 'LOG IN',
    forgetPassword: 'Forget password?',
    allRightsReserved: '© 2023. All Rights Reserved. made with',
    ACTORE: 'By ACTORE',
    resetCodeSent: 'A Reset code has been sent to your email address. Please enter the code below.',
    verifyCode: 'Verify Code',
    verify: 'Verify',
    didNotReceiveCode: "Didn't receive a code? Try again.",
    enterNewPassword: 'Please enter your new password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resetPassword: 'RESET PASSWORD',
    back: 'Back',
    complains: 'Complains',
    suggestions: 'Suggestions',
    searchPlaceholder: 'Search',
    title: 'Title',
    type: 'Type',
    message: 'Message',
    status: 'Status',
    about: 'About',
    action: 'Action',
    timeStamp: 'Time Stamp',
    name: 'Name',
    activeVouchers: 'Active Vouchers',
    deactivatedVouchers: 'Deactivated Vouchers',
    productsReviews: 'Products Reviews',
    customer: 'Customer',
    rating: 'Rating',
    notAssigned: 'Not Assigned',
    assigned: 'Assigned',
    delivery: 'Delivery',
    pickupLocation: 'Pickup Location',
    dropLocation: 'DropLocation',
    addressType: 'Address Type',
    city: 'City',
    district: 'District',
    street: 'Street',
    building: 'Building',
    floor: 'Floor',
    flat: 'Flat',
    landmark: 'Landmark',
    phoneNumbers: 'Phone Numbers',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    total: 'Total',
    paymentMethod: 'Payment Method',
    EGP: 'EGP',
    totalOrders: 'Total Orders',
    delivered: 'Delivered',
    canceledByCustomer: 'Canceled By Customer',
    canceledByStore: 'Canceled By Store',
    canceledByAdmin: 'Canceled By Admin',
    pending: 'Pending',
    orderCode: 'Order Code',
    store: 'Store',
    date: 'Date',
    ownerName: 'Owner Name',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    deactive: 'Deactive',
    sizes: 'Sizes',
    selectSizes: 'Select Sizes',
    selectspecialty: 'Select Specialty',
    colors: 'Colors',
    selectColors: 'Select Colors',
    confirm: 'Confirm',
    cancel: 'Cancel',
    loading: 'Loading...',
    availableProducts: 'Available Products',
    unavailableProducts: 'Unavailable Products',
    deactivatedProducts: 'Deactivated Products',
    foundNoProducts: 'Found No Products',
    noResultFound: 'No Result Found',
    mainCategory: 'Main Category',
    quantity: 'Quantity',
    material: 'Material',
    size: 'Size',
    color: 'Color',
    typeToSearch: 'Type to search...',
    searchBy: 'Search By',
    category: 'Category',
    numberOfOrders: '# of Orders',
    successOrders: 'Success Orders',
    returnOrders: 'Return Orders',
    addTag: 'Add Tag',
    discount: 'Discount',
    available: 'Available',
    availableFrom: 'Available From',
    changeState: 'Change State',
    delete: 'Delete',
    edit: 'Edit',
    refill: 'Refill',
    tags: 'Tags',
    selectTags: 'Select Tags',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    productInformation: 'Product Information',
    productAlbum: 'Product Album',
    productVariants: 'Product Variants',
    productPricing: 'Product Pricing',
    productTitle: 'Product Title',
    productDescription: 'Product Description',
    selectMaterial: 'Select Material',
    productImages: 'Product Images',
    photoNumber: 'Photo Number',
    addPhoto: 'Add Photo',
    noDiscount: 'No Discount',
    discountType: 'Discount Type',
    discountValue: 'Discount Value',
    percentage: 'Percentage',
    value: 'Value',
    price: 'Price',
    newPrice: 'New Price',
    next: 'Next',

    pleaseEnterTitle: "Please enter a title.",
    pleaseEnterTitle3_50: 'Please enter a title with at least 3 characters and at most 50 characters.',
    pleaseEnterDescription: "Please enter a description.",
    pleaseEnterMaterial: "Please select a material.",
    pleaseEnterPrice: "Please enter a price.",
    pleaseEnterPriceMoreThan0: "Please enter a price greater than 0.",
    pleaseEnterSpeciality: "Please select a speciality.",
    pleaseEnterMainCategory: "Please select a main category.",
    pleaseEnterSubCategory: "Please select a sub category.",
    pleaseEnterQuantity: "Please enter a quantity.",
    pleaseEnterQuantityMoreThan0: "Please enter a quantity greater than 0.",
    selectMainCategory: "Select Main Category",
    subCategory: "Sub Category",
    selectSubCategory: "Select Sub Category",
    refillProduct: "Refill Product",
    foundNoOrders: 'Found no orders .',
    customerName: 'Customer Name',
    sales: 'Sales',
    pendingOrders: 'Pending Orders',
    newProducts: 'New Products',
    approveOrder: 'Approve Order',
    cancelOrder: 'Cancel Order',
    readyForPickup: 'Ready For Pickup',
    approved: 'Approved',
    picked: 'Picked',
    pleaseEnterAddressType: 'Please enter an address type.',
    pleaseEnterAddressTypeBetween3_50: 'Please enter an address type between 3 and 50 characters.',
    pleaseEnterAddressTitle: 'Please enter an address title.',
    pleaseEnterAddressTitleBetween3_50: 'Please enter an address title between 3 and 50 characters.',
    pleaseEnterCity: 'Please enter a city.',
    pleaseEnterDistrict: 'Please enter a district.',
    pleaseEnterDistrictBetween3_50: 'Please enter a district between 3 and 50 characters.',
    pleaseEnterStreet: 'Please enter a street.',
    pleaseEnterStreetBetween3_50: 'Please enter a street between 3 and 50 characters.',
    pleaseEnterBuilding: 'Please enter a building.',
    pleaseEnterBuildingBetween3_50: 'Please enter a building between 3 and 50 characters.',
    pleaseEnterFloor: 'Please enter a floor.',
    pleaseEnterFloorBetween1_50: 'Please enter a floor between 1 and 50 characters.',
    pleaseEnterFlat: 'Please enter a flat.',
    pleaseEnterFlatBetween1_50: 'Please enter a flat between 1 and 50 characters.',
    pleaseEnterLandmark: 'Please enter a landmark.',
    pleaseEnterLandmarkBetween3_50: 'Please enter a landmark between 3 and 50 characters.',
    pleaseEnterPhoneNumber: 'Please enter a phone number.',
    pleaseEnterValidPhoneNumber: 'Please enter a valid phone number.',
    primaryPhoneNumber: 'Primary Phone Number',
    optionalPhoneNumber: 'Optional Phone Number',
    latitude: 'Latitude',
    longitude: 'Longitude',
    locateMe: 'Locate Me',
    yourLocation: 'Your Location',
    socialMediaAccounts: 'Social Media Accounts',
    facebookAccountLink: 'Facebook Account Link',
    whatsappAccountLink: 'Whatsapp Account Link',
    instagramAccountLink: 'Instagram Account Link',
    pleaseEnterStoreName: 'Please enter a store name.',
    pleaseEnterStoreNameBetween3_50: 'Please enter a store name between 3 and 50 characters.',
    pleaseEnterSlogan: 'Please enter a slogan.',
    pleaseEnterSloganBetween3_50: 'Please enter a slogan between 3 and 50 characters.',
    storeInfo: 'Store Info',
    storeName: 'Store Name',
    slogan: 'Slogan',
    save: 'Save',
    logoImage: 'Logo Image',
    changePicture: 'Change Picture',
    ownerInfo: 'Owner Info',
    ownerPhoneNumber: 'Owner Phone Number',
    ownerEmail: 'Owner Email',
    changePassword: 'Change Password',
    branches: 'Branches',
    socialMedia: 'Social Media',
    addressTitle: 'Address Title',

    fullName: 'Full Name',
    pleaseEnterFullName: 'Please enter full name.',
    pleaseEnterFullNameBetween3_50: 'Please enter full name between 3 and 50 characters.',
    email: 'Email',
    pleaseEnterValidEmail: 'Please enter a valid email.',
    phoneNumber: 'Phone Number',
    writeSlogan: 'Write Slogan',

    facebook: 'Facebook',
    whatsapp: 'Whatsapp',
    instagram: 'Instagram',

    passwordRequired: "Passwords Is required.",
    passwordLength: "Password must be at least 8 digits",
    passwordMatch: "You can't match the new password",
    passwordCurrent: "Please enter a password.",
    passwordCurrentMatch: "Please enter a password with at least 8 characters, 1 uppercase letter, 1 lowercase letter, and 1 special character.",
    passwordCannotMatch: "You can't match the new password",
    passwordDoNotMatch: "Passwords do not match.",
    current: "Current:",
    currentPassword: "Current Password",
    new: "New:",

  },
  ar: {
    home: 'الرئيسية',
    admins: 'المشرفون',
    stores: 'المتاجر',
    customers: 'العملاء',
    specialty: 'التخصص',
    products: 'المنتجات',
    orders: 'الطلبات',
    orderHistory: 'سجل الطلبات',
    drivers: 'السائقون',
    reviews: 'التقييمات',
    vouchers: 'القسائم',
    paymentMethods: 'طرق الدفع',
    logActivity: 'سجل النشاط',
    compSuggestions: 'الشكاوى والاقتراحات',
    logout: 'تسجيل الخروج',
    notes: 'ملاحظات',
    theme: 'المظهر',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    result: 'النتيجة',
    close: 'إغلاق',
    tools: 'الأدوات',
    notification: 'الإشعارات',
    profile: 'الملف الشخصي',
    hi: 'مرحبًا',
    pleaseEnterEmail: 'الرجاء إدخال عنوان البريد الإلكتروني الخاص بك. ستتلقى رسالة بريد إلكتروني لإعادة تعيين كلمة المرور.',
    emailAddress: 'عنوان البريد الإلكتروني',
    requestPasswordReset: 'طلب إعادة تعيين كلمة المرور',
    login: 'تسجيل الدخول',
    password: 'كلمة المرور',
    logIn: 'تسجيل الدخول',
    forgetPassword: 'هل نسيت كلمة المرور؟',
    allRightsReserved: '© 2023. جميع الحقوق محفوظة. صنعت بواسطة',
    ACTORE: 'ACTORE',
    resetCodeSent: 'تم إرسال رمز إعادة التعيين إلى عنوان بريدك الإلكتروني. الرجاء إدخال الرمز أدناه.',
    verifyCode: 'التحقق من الرمز',
    verify: 'تحقق',
    didNotReceiveCode: 'لم تتلقى رمزًا؟ حاول مرة أخرى.',
    enterNewPassword: 'الرجاء إدخال كلمة المرور الجديدة',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    resetPassword: 'إعادة تعيين كلمة المرور',
    back: 'العودة',
    complains: 'الشكاوى',
    suggestions: 'الاقتراحات',
    searchPlaceholder: 'بحث',
    title: 'العنوان',
    type: 'النوع',
    message: 'الرسالة',
    status: 'الحالة',
    about: 'عن',
    action: 'الإجراءات',
    timeStamp: 'الوقت',
    name: 'الاسم',
    active: 'نشط',
    inactive: 'غير نشط',
    deactive: 'معطل',
    activeVouchers: 'القسائم النشطة',
    deactivatedVouchers: 'القسائم المعطلة',
    productsReviews: 'تقييمات المنتجات',
    customer: 'العميل',
    rating: 'التقييم',
    notAssigned: 'غير معين',
    assigned: 'معين',
    delivery: 'التوصيل',
    pickupLocation: 'موقع الاستلام',
    dropLocation: 'موقع الإسقاط',
    addressType: 'نوع العنوان',
    city: 'المدينة',
    district: 'الحي',
    street: 'الشارع',
    building: 'المبنى',
    floor: 'الطابق',
    flat: 'الشقة',
    landmark: 'المعلم',
    phoneNumbers: 'أرقام الهاتف',
    subtotal: 'المجموع الفرعي',
    deliveryFee: 'رسوم التوصيل',
    total: 'المجموع',
    paymentMethod: 'طريقة الدفع',
    EGP: 'جنيه',
    totalOrders: 'إجمالي الطلبات',
    delivered: 'تم التوصيل',
    canceledByCustomer: 'تم الإلغاء من قبل العميل',
    canceledByStore: 'تم الإلغاء من قبل المتجر',
    canceledByAdmin: 'تم الإلغاء من قبل المشرف',
    pending: 'قيد الانتظار',
    orderCode: 'رمز الطلب',
    store: 'المتجر',
    date: 'التاريخ',
    ownerName: 'اسم المالك',
    sizes: 'الأحجام',
    confirm: 'تأكيد',
    selectSizes: 'اختر الأحجام',
    selectspecialty: 'اختر التخصص',
    colors: 'الألوان',
    selectColors: 'اختر الألوان',
    cancel: 'إلغاء',
    loading: 'جار التحميل...',
    availableProducts: 'المنتجات المتاحة',
    unavailableProducts: 'المنتجات غير المتاحة',
    deactivatedProducts: 'المنتجات المعطلة',
    foundNoProducts: 'لم يتم العثور على منتجات',
    noResultFound: 'لم يتم العثور على نتائج',
    all: 'الكل',
    quantity: 'الكمية',
    material: 'الخامة',
    size: 'الحجم',
    color: 'اللون',
    typeToSearch: 'اكتب للبحث',
    searchBy: 'البحث بواسطة',
    category: 'الفئة',
    numberOfOrders: 'عدد الطلبات',
    successOrders: 'الطلبات الناجحة',
    returnOrders: 'طلبات الإرجاع',
    addTag: 'إضافة علامة',
    discount: 'الخصم',
    available: 'متاح',
    availableFrom: 'متاح من',
    changeState: 'تغيير الحالة',
    delete: 'حذف',
    edit: 'تعديل',
    refill: 'إعادة تعبئة',
    tags: 'العلامات',
    selectTags: 'اختر العلامات',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل المنتج',
    productInformation: 'معلومات المنتج',
    productAlbum: 'ألبوم المنتج',
    productVariants: 'المتغيرات',
    productPricing: 'التسعير',
    productTitle: 'اسم المنتج',
    productDescription: 'وصف المنتج',
    selectMaterial: 'اختر الخامة',
    productImages: 'صور المنتج',
    photoNumber: 'رقم الصورة',
    addPhoto: 'إضافة صورة',
    noDiscount: 'بدون خصم',
    discountType: 'نوع الخصم',
    discountValue: 'قيمة الخصم',
    percentage: 'نسبة مئوية',
    value: 'قيمة',
    price: 'السعر',
    newPrice: 'السعر الجديد',
    next: 'التالي',
    pleaseEnterTitle: "من فضلك أدخل العنوان.",
    pleaseEnterTitle3_50: 'من فضلك أدخل عنوان بين 3 و 50 حرفًا.',
    pleaseEnterDescription: "من فضلك أدخل الوصف.",
    pleaseEnterMaterial: "من فضلك أدخل الخامة.",
    pleaseEnterPrice: "من فضلك أدخل السعر.",
    pleaseEnterPriceMoreThan0: "من فضلك أدخل سعر أكبر من 0.",
    pleaseEnterSpeciality: "من فضلك أدخل الخصائص.",
    pleaseEnterMainCategory: "من فضلك اختر الفئة الرئيسية.",
    pleaseEnterSubCategory: "من فضلك اختر الفئة الفرعية.",
    pleaseEnterQuantity: "من فضلك أدخل الكمية.",
    pleaseEnterQuantityMoreThan0: "من فضلك أدخل كمية أكبر من 0.",
    selectMainCategory: "من فضلك اختر الفئة الرئيسية.",
    mainCategory: "الفئة الرئيسية",
    subCategory: "الفئة الفرعية",
    selectSubCategory: "من فضلك اختر الفئة الفرعية.",
    refillProduct: "إعادة تعبئة المنتج",
    foundNoOrders: "لم يتم العثور على طلبات",
    customerName: "اسم العميل",
    sales: 'المبيعات',
    pendingOrders: 'الطلبات المعلقة',
    newProducts: 'منتجات جديدة',
    approveOrder: 'قبول الطلب',
    cancelOrder: 'إلغاء الطلب',
    readyForPickup: 'جاهز للاستلام',
    approved: 'مقبول',
    picked: 'تم الاستلام',
    pleaseEnterAddressType: 'من فضلك أدخل نوع العنوان.',
    pleaseEnterAddressTypeBetween3_50: 'من فضلك أدخل نوع العنوان بين 3 و 50 حرفًا.',
    pleaseEnterAddressTitle: 'من فضلك أدخل عنوان.',
    pleaseEnterAddressTitleBetween3_50: 'من فضلك أدخل عنوان بين 3 و 50 حرفًا.',
    pleaseEnterCity: 'من فضلك أدخل المدينة.',
    pleaseEnterDistrict: 'من فضلك أدخل المنطقة.',
    pleaseEnterDistrictBetween3_50: 'من فضلك أدخل المنطقة بين 3 و 50 حرفًا.',
    pleaseEnterStreet: 'من فضلك أدخل الشارع.',
    pleaseEnterStreetBetween3_50: 'من فضلك أدخل الشارع بين 3 و 50 حرفًا.',
    pleaseEnterBuilding: 'من فضلك أدخل المبنى.',
    pleaseEnterBuildingBetween3_50: 'من فضلك أدخل المبنى بين 3 و 50 حرفًا.',
    pleaseEnterFloor: 'من فضلك أدخل الطابق.',
    pleaseEnterFloorBetween1_50: 'من فضلك أدخل الطابق بين 1 و 50 حرفًا.',
    pleaseEnterFlat: 'من فضلك أدخل الشقة.',
    pleaseEnterFlatBetween1_50: 'من فضلك أدخل الشقة بين 1 و 50 حرفًا.',
    pleaseEnterLandmark: 'من فضلك أدخل علامة مميزة.',
    pleaseEnterLandmarkBetween3_50: 'من فضلك أدخل علامة مميزة بين 3 و 50 حرفًا.',
    pleaseEnterPhoneNumber: 'من فضلك أدخل رقم الهاتف.',
    pleaseEnterValidPhoneNumber: 'من فضلك أدخل رقم هاتف صحيح.',
    primaryPhoneNumber: 'رقم الهاتف الأساسي',
    optionalPhoneNumber: 'رقم الهاتف الاختياري',
    latitude: 'دائرة العرض',
    longitude: 'خط الطول',
    locateMe: 'تحديد موقعي',
    yourLocation: 'موقعك',
    socialMediaAccounts: 'حسابات التواصل الاجتماعي',
    facebookAccountLink: 'رابط حساب الفيسبوك',
    whatsappAccountLink: 'رابط حساب الواتساب',
    instagramAccountLink: 'رابط حساب الانستجرام',
    pleaseEnterStoreName: 'من فضلك أدخل اسم المتجر.',
    pleaseEnterStoreNameBetween3_50: 'من فضلك أدخل اسم المتجر بين 3 و 50 حرفًا.',
    pleaseEnterSlogan: 'من فضلك أدخل الشعار.',
    pleaseEnterSloganBetween3_50: 'من فضلك أدخل الشعار بين 3 و 50 حرفًا.',
    storeInfo: 'معلومات المتجر',
    storeName: 'اسم المتجر',
    slogan: 'الشعار',
    save: 'حفظ',
    logoImage: 'صورة الشعار',
    changePicture: 'تغيير الصورة',
    ownerInfo: 'معلومات المالك',
    ownerPhoneNumber: 'رقم هاتف المالك',
    ownerEmail: 'بريد المالك الإلكتروني',
    changePassword: 'تغيير كلمة المرور',
    branches: 'الفروع',
    socialMedia: 'وسائل التواصل الاجتماعي',
    addressTitle: 'عنوان',

    fullName: 'الاسم بالكامل',
    pleaseEnterFullName: 'من فضلك أدخل الاسم بالكامل.',
    pleaseEnterFullNameBetween3_50: 'من فضلك أدخل الاسم بالكامل بين 3 و 50 حرفًا.',
    email: 'البريد الإلكتروني',
    pleaseEnterValidEmail: 'من فضلك أدخل بريد إلكتروني صحيح.',
    phoneNumber: 'رقم الهاتف',
    writeSlogan: 'اكتب شعارك',

    facebook: 'فيسبوك',
    whatsapp: 'واتساب',
    instagram: 'انستجرام',

    passwordRequired: "كلمة المرور مطلوبة",
    passwordLength: "كلمة المرور يجب أن تكون 8 أحرف على الأقل",
    passwordMatch: "كلمة المرور غير متطابقة",
    passwordCurrent: "كلمة المرور الحالية",
    passwordCurrentMatch: " إدخال كلمة مرور تحتوي على 8 أحرف على الأقل، وحرف كبير واحد، وحرف صغير واحد، وحرف خاص واحد.",
    passwordCannotMatch: "كلمة المرور الجديدة لا يمكن أن تكون مطابقة لكلمة المرور الحالية",
    passwordDoNotMatch: "كلمة المرور الجديدة غير متطابقة",
    current: "الحالي",
    currentPassword: "كلمة المرور الحالية",
    new: "الجديدة",

  },
};

export default languages;