
const languages = {
  en: {
    home: 'Home',
    admins: 'Admins',
    stores: 'Stores',
    customers: 'Customers',
    specialty: 'Specialty',
    products: 'Products',
    orderHistory: 'Order History',
    drivers: 'Drivers',
    reviews: 'Reviews',
    vouchers: 'Vouchers',
    paymentMethods: 'Payment Methods',
    logActivity: 'Log Activity',
    compSuggestions: 'Comp & Suggestions',
    logout: 'Log out',
    notes: 'Notes',
    theme: 'Theme',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    result: 'Result',
    close: 'Close',
    tools: 'Tools',
    notification: 'Notification',
    profile: 'Profile',
    hi: 'Hi',
    pleaseEnterEmail: 'Please enter your email address. You will receive an email message to reset your password.',
    emailAddress: 'Email Address',
    requestPasswordReset: 'REQUEST PASSWORD RESET',
    login: 'Login',
    password: 'Password',
    logIn: 'LOG IN',
    forgetPassword: 'Forget password?',
    allRightsReserved: '© 2023. All Rights Reserved. made with',
    ACTORE: 'By ACTORE',
    resetCodeSent: 'A Reset code has been sent to your email address. Please enter the code below.',
    verifyCode: 'Verify Code',
    verify: 'Verify',
    didNotReceiveCode: "Didn't receive a code? Try again.",
    enterNewPassword: 'Please enter your new password',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resetPassword: 'RESET PASSWORD',
    back: 'Back',
    complains: 'Complains',
    suggestions: 'Suggestions',
    searchPlaceholder: 'Search',
    title: 'Title',
    type: 'Type',
    message: 'Message',
    status: 'Status',
    about: 'About',
    action: 'Action',
    timeStamp: 'Time Stamp',
    name: 'Name',
    activeVouchers: 'Active Vouchers',
    deactivatedVouchers: 'Deactivated Vouchers',
    productsReviews: 'Products Reviews',
    customer: 'Customer',
    rating: 'Rating',
    notAssigned: 'Not Assigned',
    assigned: 'Assigned',
    delivery: 'Delivery',
    pickupLocation: 'Pickup Location',
    dropLocation: 'DropLocation',
    addressType: 'Address Type',
    city: 'City',
    district: 'District',
    street: 'Street',
    building: 'Building',
    floor: 'Floor',
    flat: 'Flat',
    landmark: 'Landmark',
    phoneNumbers: 'Phone Numbers',
    subtotal: 'Subtotal',
    deliveryFee: 'Delivery Fee',
    total: 'Total',
    paymentMethod: 'Payment Method',
    EGP: 'EGP',
    totalOrders: 'Total Orders',
    delivered: 'Delivered',
    canceledByCustomer: 'Canceled By Customer',
    canceledByStore: 'Canceled By Store',
    canceledByAdmin: 'Canceled By Admin',
    pending: 'Pending',
    orderCode: 'Order Code',
    store: 'Store',
    date: 'Date',
    ownerName: 'Owner Name',
    all: 'All',
    active: 'Active',
    inactive: 'Inactive',
    deactive: 'Deactive',
    sizes: 'Sizes',
    selectSizes: 'Select Sizes',
    selectspecialty: 'Select Specialty',
    colors: 'Colors',
    selectColors: 'Select Colors',
    confirm: 'Confirm',
    cancel: 'Cancel',
    loading: 'Loading...',
    availableProducts: 'Available Products',
    unavailableProducts: 'Unavailable Products',
    deactivatedProducts: 'Deactivated Products',
    foundNoProducts: 'Found No Products',
    noResultFound: 'No Result Found',
    mainCategory: 'Main Category',
    quantity: 'Quantity',
    material: 'Material',
    size: 'Size',
    color: 'Color',
    typeToSearch: 'Type to search...',
    searchBy: 'Search By',
    category: 'Category',
    numberOfOrders: '# of Orders',
    successOrders: 'Success Orders',
    returnOrders: 'Return Orders',
    addTag: 'Add Tag',
    discount: 'Discount',
    available: 'Available',
    availableFrom: 'Available From',
    changeState: 'Change State',
    delete: 'Delete',
    edit: 'Edit',
    refill: 'Refill',
    tags: 'Tags',
    selectTags: 'Select Tags',
    addProduct: 'Add Product',
    editProduct: 'Edit Product',
    productInformation: 'Product Information',
    productAlbum: 'Product Album',
    productVariants: 'Product Variants',
    productPricing: 'Product Pricing',
    productTitle: 'Product Title',
    productDescription: 'Product Description',
    selectMaterial: 'Select Material',
    productImages: 'Product Images',
    photoNumber: 'Photo Number',
    addPhoto: 'Add Photo',
    noDiscount: 'No Discount',
    discountType: 'Discount Type',
    discountValue: 'Discount Value',
    percentage: 'Percentage',
    value: 'Value',
    price: 'Price',
    newPrice: 'New Price',
    next: 'Next',
    pleaseEnterTitle: "Please enter a title.",
    pleaseEnterTitle3_50: 'Please enter a title with at least 3 characters and at most 50 characters.',
    pleaseEnterDescription: "Please enter a description.",
    pleaseEnterMaterial: "Please select a material.",
    pleaseEnterPrice: "Please enter a price.",
    pleaseEnterPriceMoreThan0: "Please enter a price greater than 0.",
    pleaseEnterSpeciality: "Please select a speciality.",
    pleaseEnterMainCategory: "Please select a main category.",
    pleaseEnterSubCategory: "Please select a sub category.",
    pleaseEnterQuantity: "Please enter a quantity.",
    pleaseEnterQuantityMoreThan0: "Please enter a quantity greater than 0.",
    selectMainCategory: "Select Main Category",
    subCategory: "Sub Category",
    selectSubCategory: "Select Sub Category",
    refillProduct: "Refill Product",

  },
  ar: {
    home: 'الرئيسية',
    admins: 'المشرفون',
    stores: 'المتاجر',
    customers: 'العملاء',
    specialty: 'التخصص',
    products: 'المنتجات',
    orderHistory: 'سجل الطلبات',
    drivers: 'السائقون',
    reviews: 'التقييمات',
    vouchers: 'القسائم',
    paymentMethods: 'طرق الدفع',
    logActivity: 'سجل النشاط',
    compSuggestions: 'الشكاوى والاقتراحات',
    logout: 'تسجيل الخروج',
    notes: 'ملاحظات',
    theme: 'المظهر',
    darkMode: 'الوضع الداكن',
    lightMode: 'الوضع الفاتح',
    result: 'النتيجة',
    close: 'إغلاق',
    tools: 'الأدوات',
    notification: 'الإشعارات',
    profile: 'الملف الشخصي',
    hi: 'مرحبًا',
    pleaseEnterEmail: 'الرجاء إدخال عنوان البريد الإلكتروني الخاص بك. ستتلقى رسالة بريد إلكتروني لإعادة تعيين كلمة المرور.',
    emailAddress: 'عنوان البريد الإلكتروني',
    requestPasswordReset: 'طلب إعادة تعيين كلمة المرور',
    login: 'تسجيل الدخول',
    password: 'كلمة المرور',
    logIn: 'تسجيل الدخول',
    forgetPassword: 'هل نسيت كلمة المرور؟',
    allRightsReserved: '© 2023. جميع الحقوق محفوظة. صنعت بواسطة',
    ACTORE: 'ACTORE',
    resetCodeSent: 'تم إرسال رمز إعادة التعيين إلى عنوان بريدك الإلكتروني. الرجاء إدخال الرمز أدناه.',
    verifyCode: 'التحقق من الرمز',
    verify: 'تحقق',
    didNotReceiveCode: 'لم تتلقى رمزًا؟ حاول مرة أخرى.',
    enterNewPassword: 'الرجاء إدخال كلمة المرور الجديدة',
    newPassword: 'كلمة المرور الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور الجديدة',
    resetPassword: 'إعادة تعيين كلمة المرور',
    back: 'العودة',
    complains: 'الشكاوى',
    suggestions: 'الاقتراحات',
    searchPlaceholder: 'بحث',
    title: 'العنوان',
    type: 'النوع',
    message: 'الرسالة',
    status: 'الحالة',
    about: 'عن',
    action: 'الإجراءات',
    timeStamp: 'الوقت',
    name: 'الاسم',
    active: 'نشط',
    inactive: 'غير نشط',
    deactive: 'معطل',
    activeVouchers: 'القسائم النشطة',
    deactivatedVouchers: 'القسائم المعطلة',
    productsReviews: 'تقييمات المنتجات',
    customer: 'العميل',
    rating: 'التقييم',
    notAssigned: 'غير معين',
    assigned: 'معين',
    delivery: 'التوصيل',
    pickupLocation: 'موقع الاستلام',
    dropLocation: 'موقع الإسقاط',
    addressType: 'نوع العنوان',
    city: 'المدينة',
    district: 'الحي',
    street: 'الشارع',
    building: 'المبنى',
    floor: 'الطابق',
    flat: 'الشقة',
    landmark: 'المعلم',
    phoneNumbers: 'أرقام الهاتف',
    subtotal: 'المجموع الفرعي',
    deliveryFee: 'رسوم التوصيل',
    total: 'المجموع',
    paymentMethod: 'طريقة الدفع',
    EGP: 'جنيه',
    totalOrders: 'إجمالي الطلبات',
    delivered: 'تم التوصيل',
    canceledByCustomer: 'تم الإلغاء من قبل العميل',
    canceledByStore: 'تم الإلغاء من قبل المتجر',
    canceledByAdmin: 'تم الإلغاء من قبل المشرف',
    pending: 'قيد الانتظار',
    orderCode: 'رمز الطلب',
    store: 'المتجر',
    date: 'التاريخ',
    ownerName: 'اسم المالك',
    sizes: 'الأحجام',
    confirm: 'تأكيد',
    selectSizes: 'اختر الأحجام',
    selectspecialty: 'اختر التخصص',
    colors: 'الألوان',
    selectColors: 'اختر الألوان',
    cancel: 'إلغاء',
    loading: 'جار التحميل...',
    availableProducts: 'المنتجات المتاحة',
    unavailableProducts: 'المنتجات غير المتاحة',
    deactivatedProducts: 'المنتجات المعطلة',
    foundNoProducts: 'لم يتم العثور على منتجات',
    noResultFound: 'لم يتم العثور على نتائج',
    all: 'الكل',
    quantity: 'الكمية',
    material: 'الخامة',
    size: 'الحجم',
    color: 'اللون',
    typeToSearch: 'اكتب للبحث',
    searchBy: 'البحث بواسطة',
    category: 'الفئة',
    numberOfOrders: 'عدد الطلبات',
    successOrders: 'الطلبات الناجحة',
    returnOrders: 'طلبات الإرجاع',
    addTag: 'إضافة علامة',
    discount: 'الخصم',
    available: 'متاح',
    availableFrom: 'متاح من',
    changeState: 'تغيير الحالة',
    delete: 'حذف',
    edit: 'تعديل',
    refill: 'إعادة تعبئة',
    tags: 'العلامات',
    selectTags: 'اختر العلامات',
    addProduct: 'إضافة منتج',
    editProduct: 'تعديل المنتج',
    productInformation: 'معلومات المنتج',
    productAlbum: 'ألبوم المنتج',
    productVariants: 'المتغيرات',
    productPricing: 'التسعير',
    productTitle: 'اسم المنتج',
    productDescription: 'وصف المنتج',
    selectMaterial: 'اختر الخامة',
    productImages: 'صور المنتج',
    photoNumber: 'رقم الصورة',
    addPhoto: 'إضافة صورة',
    noDiscount: 'بدون خصم',
    discountType: 'نوع الخصم',
    discountValue: 'قيمة الخصم',
    percentage: 'نسبة مئوية',
    value: 'قيمة',
    price: 'السعر',
    newPrice: 'السعر الجديد',
    next: 'التالي',
    pleaseEnterTitle: "من فضلك أدخل العنوان.",
    pleaseEnterTitle3_50: 'من فضلك أدخل عنوان بين 3 و 50 حرفًا.',
    pleaseEnterDescription: "من فضلك أدخل الوصف.",
    pleaseEnterMaterial: "من فضلك أدخل الخامة.",
    pleaseEnterPrice: "من فضلك أدخل السعر.",
    pleaseEnterPriceMoreThan0: "من فضلك أدخل سعر أكبر من 0.",
    pleaseEnterSpeciality: "من فضلك أدخل الخصائص.",
    pleaseEnterMainCategory: "من فضلك اختر الفئة الرئيسية.",
    pleaseEnterSubCategory: "من فضلك اختر الفئة الفرعية.",
    pleaseEnterQuantity: "من فضلك أدخل الكمية.",
    pleaseEnterQuantityMoreThan0: "من فضلك أدخل كمية أكبر من 0.",
    selectMainCategory: "من فضلك اختر الفئة الرئيسية.",
    mainCategory: "الفئة الرئيسية",
    subCategory: "الفئة الفرعية",
    selectSubCategory: "من فضلك اختر الفئة الفرعية.",
    refillProduct: "إعادة تعبئة المنتج",
  },
};

export default languages;